### ISSUE TITLE
terminate called after throwing an instance of 'cl::BuildError'

### ISSUE THREAD

**Issue by Weaksfx** [sp-hash/TeamBlackMiner#213]
Problem appeared in 1.37 on RaveOS.
 ![image](https://user-images.githubusercontent.com/43636645/148784142-afbfcd6e-ae28-4e95-8309-0a67dd8e54d5.png)

**Comment by sp-hash** [comment]
Perhaps a cuda 18.4 build  will help. We have some other bugs that needs to be fixed first.

**Comment by sp-hash** [comment]
fixed in v1.38

**Comment by oiG8Uchi** [comment]
![image](https://user-images.githubusercontent.com/95996550/149042045-11494ca3-f137-448d-92c9-e95d3a489e60.png)

**Comment by sp-hash** [comment]
try to run
sudo apt-get install --only-upgrade libstdc++6

**Comment by oiG8Uchi** [comment]
still doesn't work, if all the graphics cards used are nvidia, this problem does not occur
